### ISSUE TITLE
Possibility to send emails via `curl`?

### ISSUE THREAD

**Issue by SubtleMuffin** [fastmail/JMAP-Samples#21]
Hello -- I am wondering if it is possible to send an email (possibly with attachments) via `curl`? It would save a lot of time tinkering the given examples.

Mailgun can achieve this via

```shell
curl -s --user "api:$MAILGUN_API_KEY" "https://api.mailgun.net/v3/$MAILGUN_DOMAIN/messages"
      -F from="sender@email.com"
      -F to="receiver@email.com"
      -F subject="Subject"
      -F text="`export`"
      -F attachment="@attachment.pdf"
```

This is extremely useful especially when incorporating email notifications in CI/CD workflows.

**Comment by mmcclimon** [comment]
You can certainly use curl to send JMAP requests, but to be frank it's not ever going to be as straightforward as your Mailgun example. You're always going to need to post a JSON request containing an `EmailSubmission/set` call, and personally I find doing that with curl to be more tedious than passing multiple form fields with `-F`.

If you're still interested we can definitely come up with a real example! When I've needed/wanted to send emails with JMAP via the command line, I don't use curl directly but use some other tooling with access to some conveniences for authentication and building the JMAP calls.

**Comment by SubtleMuffin** [comment]
Thank you, @mmcclimon! Yes, that would be lovely to have an example with command-line tools. I assume tools such as `jq` are going to be used.

The reason that I am asking is that I am using the GitLab CI/CD system to automatically typeset a resume and send that to my mailbox --

```yml
stages:
    - typeset
    - notify

typeset:
  stage: typeset
  image: subtlemuffin/latex
  script:
    - latexmk -pdf
  artifacts:
    paths:
      - "*.pdf"

send:
  stage: notify
  image: alpine:latest
  script:
    - apk --no-cache add curl
    - >
      curl -s --user "api:$MAILGUN_API_KEY" "https://api.mailgun.net/v3/$MAILGUN_DOMAIN/messages"
      -F from="sender@email.com"
      -F to="receiver@email.com"
      -F subject="Resume -- $CI_COMMIT_SHORT_SHA"
      -F text="`export`"
      -F attachment="@resume.pdf"
```

For this `note-to-self` type, I guess an `Email/set` JMAP call would be sufficient. If you could provide an example that can also send an attachment, that would be even better!

Thanks!
